### ISSUE TITLE
Redmine 3.x compatibility

### ISSUE THREAD

**Issue by megheaiulian** [themondays/redmine_worktime_log#4]
On Redmine 3.x the plugin triggers SQL errors.

**Comment by themondays** [comment]
Thank, will plan further fixes.

**Comment by tolstenko** [comment]
I need this too! Thanks.

**Comment by themondays** [comment]
Hi,
You're running under MySQL?

**Comment by fwolfst** [comment]
@themondays Are you planning a new release anytime soon?

**Comment by themondays** [comment]
Hi,
Yes, but due to lack of time it's delayed.

Thanks
